### ISSUE TITLE
life360.exceptions.LoginError: aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden'

### ISSUE THREAD

**Issue by michelscholte** [ryanbuckner/life360-plugin#1]
Hi Ryan,
I saw that you had made a mention of the error at pnbrucker's github, but unfortunately his reply did not provide a solution.  My question now is, if you got it working by now? After all, I have the same error and want to create a pythonscript for Domoticz. I would like to hear from you. Thanks in advance.

**Comment by ryanbuckner** [comment]
I wasn’t able to get it working Ryan ***@***.*** Nov 7, 2024, at 2:18 PM, michelscholte ***@***.***> wrote:﻿
Hi Ryan,
I saw that you had made a mention of the error at pnbrucker's github, but unfortunately his reply did not provide a solution.  My question now is, if you got it working by now? After all, I have the same error and want to create a pythonscript for Domoticz. I would like to hear from you. Thanks in advance.

**Comment by michelscholte** [comment]
Too bad. Thanks for your quick reply.
